DROP TABLE IF EXISTS peeps;
DROP SEQUENCE IF EXISTS peeps_id_seq;

CREATE SEQUENCE IF NOT EXISTS peeps_id_seq;
CREATE TABLE peeps (
    id SERIAL PRIMARY KEY,
    author VARCHAR(255) NOT NULL,
    peep TEXT NOT NULL,
    time_posted TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
